### ISSUE TITLE
How to connect an application

### ISSUE THREAD

**Issue by Lampe96** [hyperledger-labs/fablo#292]
Hi, i've already set-up the network and everything is going fine but i've no idea how to connect it with one or more application (how to communicate with the chaincode). Someone has some solution? Thanks

I'm leaving here the configuration file:

```json
{
  "$schema": "https://github.com/softwaremill/fablo/releases/download/1.0.0/schema.json",
  "global": {
    "fabricVersion": "2.4.1",
    "tls": true
  },
  "orgs": [
    {
      "organization": {
        "name": "Orderer",
        "domain": "orderer.project.it"
      },
      "orderers": [
        {
          "groupName": "group1",
          "type": "raft",
          "instances": 1
        }
      ],
      "tools": {}
    },
    {
      "organization": {
        "name": "Home1",
        "domain": "home1.project.it"
      },
      "peer": {
        "instances": 2,
        "db": "CouchDb"
      },
      "tools": {}
    },
    {
      "organization": {
        "name": "Home2",
        "domain": "home2.project.it"
      },
      "peer": {
        "instances": 2,
        "db": "CouchDb"
      },
      "tools": {}
    }
  ],
  "channels": [
    {
      "name": "channel1",
      "orgs": [
        {
          "name": "Home1",
          "peers": [
            "peer0",
            "peer1"
          ]
        },
        {
          "name": "Home2",
          "peers": [
            "peer0",
            "peer1"
          ]
        }
      ]
    }
  ],
  "chaincodes": [
    {
      "name": "chaincode1",
      "version": "0.0.1",
      "lang": "java",
      "channel": "channel1",
      "directory": "../chaincode-java-simple"
    }
  ]
}
```

**Comment by dzikowski** [comment]
There are various ways how to do it. Probably the simplest one is to use Fablo REST (https://github.com/softwaremill/fablo-rest). You can just include for organization `"fabloRest": true` and you will have REST API to your blockchain network. See README in Fablo REST for some CURL samples.

Besides you can connect with SDKs for Node.js, Go or JVM. In order to do it, you can see how we connect manually with Fabric with Fablo REST - have a look at [this file](https://github.com/softwaremill/fablo-rest/blob/main/src/NetworkPool.ts). Alternatively you can use connection profiles that are generated by Fablo in `fablo-target` directory.
